<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="P_Machine" Id="{0fd8fc40-2ee5-42de-b55f-c83385416cf6}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM P_Machine
VAR
	startButton			: ButtonNO;
	requestButton		: ButtonNO;
	appleJuiceContoller	: PumpControllerWithLogger(requestButton, 0, 10_000);
	orangeJuiceContoller: PumpControllerWithLogger(requestButton, 0, 5_000);
	signalTower			: SignalTower;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[appleJuiceContoller();
orangeJuiceContoller();

IF startButton.RisingTrigger THEN
	appleJuiceContoller.Enable();
	orangeJuiceContoller.Enable();
END_IF

IF appleJuiceContoller.IsDisabled THEN
	signalTower.SwitchOffGreen();
	signalTower.SwitchOffRed();
ELSIF appleJuiceContoller.IsEnabled THEN
	signalTower.SwitchOnGreen();
	signalTower.SwitchOffRed();
ELSIF appleJuiceContoller.IsPumping THEN
	signalTower.SwitchOnGreen();
	signalTower.SwitchOnRed();
ELSIF appleJuiceContoller.IsPumpingComplete THEN
	signalTower.SwitchOnGreen();
	signalTower.SwitchOffRed();
END_IF
	]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>