<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="ButtonNO" Id="{9648fb86-2586-4f86-af45-2503960afbd3}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ButtonNO
VAR
	bInput	AT%I*	: BOOL;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Property Name="IsPressed" Id="{399b64f0-f69f-44c3-93ed-d0388813c38c}">
      <Declaration><![CDATA[PROPERTY IsPressed : BOOL]]></Declaration>
      <Get Name="Get" Id="{d52789a7-20c7-4c29-a7bf-18c548688d6a}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsPressed := bInput;]]></ST>
        </Implementation>
      </Get>
    </Property>
    <Property Name="IsReleased" Id="{a989c524-856f-410a-91b7-e81596cf9c4d}">
      <Declaration><![CDATA[PROPERTY IsReleased : BOOL]]></Declaration>
      <Get Name="Get" Id="{402f5afa-cbb7-44b0-93f6-071a8ad43338}">
        <Declaration><![CDATA[VAR
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IsReleased := NOT IsPressed;]]></ST>
        </Implementation>
      </Get>
    </Property>
  </POU>
</TcPlcObject>