<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="TestFbInit" Id="{8724d832-5ef8-4b86-a5d8-81478abc2cf2}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK TestFbInit
VAR
	nValue	: INT := 5;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="FB_Init" Id="{3b355824-736a-4084-8c21-3ed946f7adce}">
      <Declaration><![CDATA[//FB_Init is always available implicitly and it is used primarily for initialization.
//The return value is not evaluated. For a specific influence, you can also declare the
//methods explicitly and provide additional code there with the standard initialization
//code. You can evaluate the return value.
METHOD FB_Init: BOOL
VAR_INPUT
    bInitRetains: BOOL; // TRUE: the retain variables are initialized (reset warm / reset cold)
    bInCopyCode: BOOL;  // TRUE: the instance will be copied to the copy code afterward (online change)
	wartosc		: INT;   
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[nValue := wartosc;]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>